application:
  port: 8000
  hmac_secret: "long-encrypted-secret-key-for-message-verification-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "ultima"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  auth_token: "gloria-invigilata"
  timeout_milliseconds: 10000