name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  
    paths:
      - 'production_rust/Cargo.toml'
      - 'production_rust/Cargo.lock'
jobs:
  security_audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
